// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfqpuxijcbdhtqizpcdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mcXB1eGlqY2JkaHRxaXpwY2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxOTcwMDQsImV4cCI6MjA1Mjc3MzAwNH0.mtoqgXuakygpEeHd6WwndduIGVSMXcc9wqFvCCgqB0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);